# Workflow for deploying both FoodApp (Web App) and API project

name: Build and deploy ASP.Net Core apps to Azure Web Apps - FoodApp & API

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run Tests 
        run: |
            echo "Running unit tests..."
            dotnet test --configuration Release --no-build --logger "console;verbosity=detailed" 

      - name: dotnet publish FoodWasteApp
        run: dotnet publish FoodWasteApp/FoodWasteApp.csproj -c Release -o ${{env.DOTNET_ROOT}}/FoodWasteApp

      - name: dotnet publish API
        run: dotnet publish API/API.csproj -c Release -o ${{env.DOTNET_ROOT}}/API  

      - name: Upload artifact for FoodApp deployment
        uses: actions/upload-artifact@v3
        with:
          name: FoodWasteApp-1
          path: ${{env.DOTNET_ROOT}}/FoodWasteApp

      - name: Upload artifact for API deployment
        uses: actions/upload-artifact@v3
        with:
          name: FoodWasteApp-API
          path: ${{env.DOTNET_ROOT}}/API

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-foodapp.outputs.webapp-url }}  
    permissions:
      id-token: write 

    steps:
      - name: Download artifact from build job (FoodWasteApp)
        uses: actions/download-artifact@v3
        with:
          name: FoodWasteApp  
          path: ./FoodWasteAppArtifact

      - name: Download artifact from build job (API)
        uses: actions/download-artifact@v3
        with:
          name: FoodWasteApp-API 
          path: ./APIArtifact

      - name: List Files in FoodAppArtifact
        run: ls ./FoodWasteAppArtifact

      - name: List Files in APIArtifact
        run: ls ./APIArtifact

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_46E2C79F4BD44423A13B2938A1827C7F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3990D8CA9AE14CDEBE2B5E3ECC30AD7C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9D2FDBBD143F45E0A0BEE6810E5809BF }}

      - name: Deploy FoodApp to Azure Web App
        id: deploy-to-foodapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'FoodWasteApp-1' 
          slot-name: 'Production'
          package: ./FoodWasteAppArtifact  

      - name: Deploy API to Azure Web App
        id: deploy-to-api
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'FoodWasteApp-API'  
          slot-name: 'Production'
          package: ./APIArtifact
